[env:esp32-s3-devkitc-1]
board = ESP-General
build_src_filter = ${env.build_src_filter} +<../boards/ESP-General>

build_flags =
    ${env.build_flags}
    -Iboards/ESP-General
    -DUSB_as_HID=1

    ; --- GROVE PINS ---
    -DGROVE_SDA=8
    -DGROVE_SCL=45

    ; --- IR LED PIN ---
    -DLED=40
    -DLED_ON=HIGH
    -DLED_OFF=LOW

    ; --- SD CARD PINS ---
    -DSDCARD_CS=-1
    -DSDCARD_SCK=-1
    -DSDCARD_MISO=-1
    -DSDCARD_MOSI=-1

    -DUSE_HSPI_PORT=1

    ; --- TFT VARS (ST7735 1.8 inch 128x160) ---
    -DST7735_DRIVER=1
    -DTFT_WIDTH=128
    -DTFT_HEIGHT=160
    -DTFT_CS=10
    -DTFT_DC=8
    -DTFT_RST=9
    -DTFT_MOSI=11
    -DTFT_SCLK=12
    -DTFT_BL=7
